# This is a basic workflow to publish 
name: Auto publish to public site

# Controls when push to branch main
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extened: true
          
      - name: Build content to public site
        working-directory: ./
        run: hugo --minify -c --cleanDestinationDir
        
      - name: Deploy and publish updates
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/gh-pages' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
            
        
        
        
        
