# This is a basic workflow to publish 
name: Auto publish to public site

# Controls when push to branch main
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: cheout out repo
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extened: true
          
      - name: Build content to public site
        working-directory: ./
        run: hugo --minify -gc --cleanDestinationDir
        
      - name: Deploy and publish updates
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/gh-pages' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
            
        
        
        
        
